# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "postgres" do |postgres|
        postgres.vm.box = "ubuntu/trusty64"
        postgres.vm.network "private_network", ip: "192.168.33.9"
        postgres.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
    end
    config.vm.define "ghost" do |ghost|
        ghost.vm.box = "ubuntu/trusty64"
        ghost.vm.network "private_network", ip: "192.168.33.10"
        ghost.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
    end
end
