.PHONY: build push run clean

run:
	ansible-container run

stop:
	ansible-container stop

build:
	ansible-container build

push:
	ansible-container push

clean:
	ansible-container destroy
	rm -rf ansible-deployment ghostdata
